# Generated by Django 5.2 on 2025-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_shortenedurl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
